# MP Configuration File
# This file is used by mp.sh and the Grading System to determine environment settings.
# It will be overwritten by the TA during the Official Grading phase.

# Assignment Identifier
ASSIGNMENT="mp0"
REPOSITORY_NAME="ntuos2026-mp0"
DOCKER_IMAGE="ntuos/mpx"
ACTION_IMAGE="ghcr.io/ntu-csieos26spring/mpx"

# Homework Deadline (ISO 8601)
DEADLINE="2026-06-30T23:59:59+08:00"

# Additional Environmental Variables

# TA Email Whitelist (Space separated)
# Any commit by these emails will be SKIPPED by the local test runner
# and EXCLUDED from the official grading target.
TA_EMAILS="ta_lead@ntu.edu.tw ta2@ntu.edu.tw"
