name: Autograding Tests
'on':
  push:
    branches:
      - ntuos/mp2-submit
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: 'github.actor != ''github-classroom[bot]'''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Environment
        run: ./mp2.sh pull

      - name: Decrypt Private Tests
        run: >
          openssl enc -aes-256-cbc -d -in test/private_tests.zip.enc -out
          test/private.zip -k ${{ secrets.DECRYPT_PASSWORD }} -pbkdf2

      - name: Unzip Private Tests
        run: cd test && unzip private.zip

      - name: Run all the tests
        id: test-all
        run: |
          function get_from_score() {
              "$@" | tail -n 1 | sed 's/Score: \([0-9]*\)\/\([0-9]*\)/\1/' || echo 0
          }

          SLAB=$(get_from_score ./mp2.sh test slab)
          echo "Slab structure grade: $SLAB"

          FUNC=$(get_from_score ./mp2.sh test func)
          echo "Functionality test grade: $FUNC"

          thresh=66

          if [[ $FUNC -ge $thresh ]]; then
              echo "Functionality test score is at least $thresh, run bonus test"
              LIST=$(get_from_score ./mp2.sh test list)
              echo "Bonus (list api): $LIST"
              CACHE=$(get_from_score ./mp2.sh test cache)
              echo "Bonus (in-cache): $CACHE"
              BONUS=$(( LIST + CACHE ))
          else
              echo "Functionality test score is not greater than $thresh, skip bonus test"
              BONUS=0
          fi

          PRIVATE=$(get_from_score ./mp2.sh test private)
          echo "Private test grade: $PRIVATE"

          SCORE=$(( SLAB + FUNC + BONUS + PRIVATE ))
          STUDENT_ID=$(cat ./student_id.txt)
          echo "SCORE=$SCORE" >> $GITHUB_ENV
          echo "STUDENT_ID=$STUDENT_ID" >> $GITHUB_ENV

          echo "Student $STUDENT_ID got score: $SCORE"
        shell: bash

      - name: Submit grade to TA's repo
        run: |
          git config --global user.name "Student Bot"
          git config --global user.email "student@github.com"

          git clone "https://$GITHUB_ACTOR:${{ secrets.TA_REPO_TOKEN }}@github.com/${{ secrets.TA_REPO }}.git" grades_repo
          cd grades_repo

          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "$STUDENT_ID,$SCORE,$TIMESTAMP" | tee -a grades.csv

          git add grades.csv
          git commit -m "Update grade for $STUDENT_ID"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TA_REPO: ${{ secrets.TA_REPO }}
          TA_REPO_TOKEN: ${{ secrets.TA_REPO_TOKEN }}
